import React, { useState } from "react";
import {
  CashPositionMetrics,
  FinancialAnalyticsSummary,
  ReconciledRecord,
  ReconciliationMetrics,
} from "../types";
import {
  FileText,
  Download,
  Printer,
  Sparkles,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  Building,
  Calendar,
} from "lucide-react";
import { exportReconciliationToCSV } from "../services/reportService";

interface ReportsTabProps {
  metrics: ReconciliationMetrics;
  analytics: FinancialAnalyticsSummary;
  cashPosition: CashPositionMetrics;
  records: ReconciledRecord[];
}

export const ReportsTab: React.FC<ReportsTabProps> = ({
  metrics,
  analytics,
  cashPosition,
  records,
}) => {
  const [reportTitle, setReportTitle] = useState("Finance Controller Close Pack");
  const [reportingEntity, setReportingEntity] = useState("Acme Global Payments Ltd.");
  const [reportDate] = useState(() => new Date().toISOString().substring(0, 10));

  const unresolvedRecords = records.filter((r) => r.match_status !== "MATCHED" && !r.resolved);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Action Bar */}
      <div className="bg-zinc-900/40 rounded-xl p-4 border border-zinc-800 flex flex-wrap items-center justify-between gap-3 shadow-sm print:hidden">
        <div>
          <h2 className="text-sm font-bold text-white flex items-center gap-2">
            <FileText className="w-4 h-4 text-blue-400" />
            Formal Financial Close & Controller Reporting
          </h2>
          <p className="text-xs text-zinc-400">
            Export comprehensive reconciliation packets for audit committees, external auditors, and CFO review
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => exportReconciliationToCSV(records)}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-zinc-800 hover:bg-zinc-700 text-zinc-200 border border-zinc-700 transition cursor-pointer"
          >
            <Download className="w-4 h-4 text-zinc-400" />
            <span>Export CSV Dataset</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-4 py-1.5 rounded-lg text-xs font-semibold bg-blue-600 hover:bg-blue-500 text-white shadow-sm transition cursor-pointer"
          >
            <Printer className="w-4 h-4" />
            <span>Print / Save PDF Report</span>
          </button>
        </div>
      </div>

      {/* Printable Report Document Sheet */}
      <div
        id="printable-controller-report"
        className="bg-zinc-950 rounded-xl border border-zinc-800 p-8 shadow-sm space-y-8 print:bg-white print:text-black print:border-none print:shadow-none print:p-0"
      >
        {/* Document Header */}
        <div className="border-b border-zinc-800 print:border-slate-300 pb-6 flex flex-wrap justify-between items-start gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs font-bold font-mono tracking-widest text-blue-400 uppercase">
                FIRA CONTROLLER MEMORANDUM
              </span>
              <span className="text-[10px] px-2 py-0.5 rounded bg-zinc-900 text-zinc-300 border border-zinc-800 print:border-slate-300">
                AUDIT-READY
              </span>
            </div>
            <h1 className="text-2xl font-extrabold text-white print:text-black tracking-tight">
              {reportTitle}
            </h1>
            <p className="text-xs text-zinc-400 print:text-slate-600 mt-1">
              Reporting Entity: <strong className="text-zinc-200 print:text-black">{reportingEntity}</strong> · Date: {reportDate}
            </p>
          </div>

          <div className="text-right text-xs space-y-1">
            <div className="text-zinc-400 print:text-slate-600">Verification Standard:</div>
            <div className="font-semibold text-emerald-400 print:text-emerald-700">
              Deterministic Multi-Source Parity
            </div>
            <div className="text-[11px] text-zinc-500 print:text-slate-500">
              Generated by FIRA Finance Controller
            </div>
          </div>
        </div>

        {/* Section 1: Executive Summary */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold tracking-wider uppercase text-blue-400 print:text-indigo-800">
            1. Executive Summary & Controller Opinion
          </h3>
          <p className="text-xs text-zinc-300 print:text-slate-800 leading-relaxed bg-zinc-900/60 print:bg-slate-50 p-4 rounded-xl border border-zinc-800 print:border-slate-200">
            During the evaluated financial close period, FIRA performed automated three-way reconciliation across{" "}
            <strong>{metrics.totalRecords} transactions</strong> representing a gross volume of{" "}
            <strong>₹{analytics.totalTransactionValue.toLocaleString("en-IN")}</strong>. The engine achieved an automated match rate of{" "}
            <strong>{metrics.matchRate.toFixed(1)}%</strong> and an empirical ground-truth verification accuracy of{" "}
            <strong>{metrics.accuracy.toFixed(1)}%</strong>. A total of{" "}
            <strong>{metrics.totalExceptions} exceptions</strong> were isolated with an aggregate financial exposure of{" "}
            <strong>₹{metrics.totalExceptionValue.toLocaleString("en-IN")}</strong>. Management recommends immediate settlement inquiry for amount variances and gateway reconciliation credit note reconciliation.
          </p>
        </div>

        {/* Section 2: Core KPI Summary Table */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold tracking-wider uppercase text-blue-400 print:text-indigo-800">
            2. Key Reconciliation Performance Indicators
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
            <div className="bg-zinc-900/60 print:bg-slate-100 p-3 rounded-lg border border-zinc-800 print:border-slate-300">
              <span className="text-zinc-400 print:text-slate-600 block text-[10px]">Reconciliation Match Rate</span>
              <span className="text-lg font-bold font-mono text-emerald-400 print:text-emerald-700">
                {metrics.matchRate.toFixed(1)}%
              </span>
            </div>

            <div className="bg-zinc-900/60 print:bg-slate-100 p-3 rounded-lg border border-zinc-800 print:border-slate-300">
              <span className="text-zinc-400 print:text-slate-600 block text-[10px]">Accuracy (GT Verified)</span>
              <span className="text-lg font-bold font-mono text-blue-400 print:text-indigo-800">
                {metrics.accuracy.toFixed(1)}%
              </span>
            </div>

            <div className="bg-zinc-900/60 print:bg-slate-100 p-3 rounded-lg border border-zinc-800 print:border-slate-300">
              <span className="text-zinc-400 print:text-slate-600 block text-[10px]">Total Exception Exposure</span>
              <span className="text-lg font-bold font-mono text-yellow-400 print:text-amber-700">
                ₹{metrics.totalExceptionValue.toLocaleString("en-IN")}
              </span>
            </div>

            <div className="bg-zinc-900/60 print:bg-slate-100 p-3 rounded-lg border border-zinc-800 print:border-slate-300">
              <span className="text-zinc-400 print:text-slate-600 block text-[10px]">Processing Throughput</span>
              <span className="text-lg font-bold font-mono text-white print:text-black">
                {metrics.throughput.toFixed(0)} r/s
              </span>
            </div>
          </div>
        </div>

        {/* Section 3: Cash Position & Settlement Tie-Out */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold tracking-wider uppercase text-blue-400 print:text-indigo-800">
            3. Cash Position & Settlement Bridge
          </h3>
          <div className="border border-zinc-800 print:border-slate-300 rounded-lg overflow-hidden text-xs">
            <table className="w-full text-left">
              <thead className="bg-zinc-900/80 print:bg-slate-200 text-zinc-400 print:text-slate-700 font-semibold text-[10px] uppercase tracking-wider">
                <tr>
                  <th className="p-2.5">Reconciliation Component</th>
                  <th className="p-2.5 text-right">Monetary Value (INR)</th>
                  <th className="p-2.5">Notes</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800/60 print:divide-slate-300 text-zinc-300 print:text-black">
                <tr>
                  <td className="p-2.5 font-medium">Gross Transaction Volume (Source A Ledger)</td>
                  <td className="p-2.5 text-right font-mono font-bold">₹{cashPosition.grossTransactionValue.toLocaleString("en-IN")}</td>
                  <td className="p-2.5 text-zinc-400 print:text-slate-600">Total authorized checkout transactions</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-medium">Less: Payment Gateway Processing Fees (MDR)</td>
                  <td className="p-2.5 text-right font-mono text-red-400 print:text-rose-700">−₹{cashPosition.totalFees.toLocaleString("en-IN")}</td>
                  <td className="p-2.5 text-zinc-400 print:text-slate-600">Contractual merchant discount rates</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-medium">Less: GST Surcharges on Fees (18%)</td>
                  <td className="p-2.5 text-right font-mono text-red-400 print:text-rose-700">−₹{cashPosition.totalTaxes.toLocaleString("en-IN")}</td>
                  <td className="p-2.5 text-zinc-400 print:text-slate-600">Tax invoice statutory deduction</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-medium">Less: Unresolved Exceptions Held in Escrow / Dispute</td>
                  <td className="p-2.5 text-right font-mono text-yellow-400 print:text-amber-700">−₹{cashPosition.unresolvedAmounts.toLocaleString("en-IN")}</td>
                  <td className="p-2.5 text-zinc-400 print:text-slate-600">Discrepant amounts flagged for second-tier review</td>
                </tr>
                <tr className="bg-zinc-900/60 print:bg-slate-100 font-bold">
                  <td className="p-2.5 text-emerald-400 print:text-emerald-700">Estimated Net Cash Liquidity Position</td>
                  <td className="p-2.5 text-right font-mono text-emerald-400 print:text-emerald-700">₹{cashPosition.estimatedNetPosition.toLocaleString("en-IN")}</td>
                  <td className="p-2.5 text-zinc-300 print:text-slate-700">Cleared funds expected in bank accounts</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* Section 4: Unresolved Exceptions Requiring Sign-off */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold tracking-wider uppercase text-blue-400 print:text-indigo-800">
            4. Unresolved Exceptions Schedule (Sample)
          </h3>
          <div className="border border-zinc-800 print:border-slate-300 rounded-lg overflow-hidden text-xs">
            <table className="w-full text-left">
              <thead className="bg-zinc-900/80 print:bg-slate-200 text-zinc-400 print:text-slate-700 font-semibold text-[10px] uppercase tracking-wider">
                <tr>
                  <th className="p-2.5">Txn ID</th>
                  <th className="p-2.5">Merchant</th>
                  <th className="p-2.5">Category</th>
                  <th className="p-2.5">Discrepancy (INR)</th>
                  <th className="p-2.5">Root Cause / Rule Failed</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800/60 print:divide-slate-300 text-zinc-300 print:text-black">
                {unresolvedRecords.slice(0, 5).map((rec) => (
                  <tr key={rec.id}>
                    <td className="p-2.5 font-mono font-semibold">{rec.transaction_id}</td>
                    <td className="p-2.5">{rec.customer_name}</td>
                    <td className="p-2.5">{rec.exception_type.replace(/_/g, " ")}</td>
                    <td className="p-2.5 font-mono font-bold text-yellow-400 print:text-amber-700">
                      ₹{(rec.difference_amount || rec.amount).toLocaleString("en-IN")}
                    </td>
                    <td className="p-2.5 text-zinc-400 print:text-slate-600 truncate max-w-xs">{rec.rule_failed}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Section 5: Sign-off & Signatures */}
        <div className="pt-6 border-t border-zinc-800 print:border-slate-300 grid grid-cols-2 gap-8 text-xs text-zinc-400 print:text-slate-600">
          <div>
            <div className="h-12 border-b border-zinc-700 print:border-slate-400 mb-2"></div>
            <p className="font-semibold text-zinc-200 print:text-black">Prepared By: Lead Financial Controller</p>
            <p className="text-[11px]">Audit & Financial Compliance Division</p>
          </div>
          <div>
            <div className="h-12 border-b border-zinc-700 print:border-slate-400 mb-2"></div>
            <p className="font-semibold text-zinc-200 print:text-black">Reviewed & Approved By: Chief Financial Officer (CFO)</p>
            <p className="text-[11px]">Treasury & Capital Management</p>
          </div>
        </div>
      </div>
    </div>
  );
};
